import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import React, { Suspense } from "react";
import Analytics from "@/components/Analytics";
import { Cherry_Bomb_One } from 'next/font/google';
// import { Oi } from 'next/font/google';

// const oi = Oi({
//   subsets: ['latin'],
//   weight: '400', // Oi only has one weight
//   display: 'swap',
// });

const cherryBombOne = Cherry_Bomb_One({
  subsets: ['latin'],
  weight: '400', // Cherry Bomb One has only 400
  display: 'swap',
});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const cascadiaMono = Geist_Mono({
//   variable: "--font-cascadia-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cherryBombOne.className} antialiased`}
      >
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
          strategy="afterInteractive"
        />

        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);} 
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}', { page_path: window.location.pathname });
          `}
        </Script>

        {/* Client-side analytics helper for SPA route changes */}
        <Suspense fallback={null}>
          <Analytics />
        </Suspense>

        {children}
      </body>
    </html>
  );
}
