import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Cherry_Bomb_One } from 'next/font/google';
// import { Oi } from 'next/font/google';

// const oi = Oi({
//   subsets: ['latin'],
//   weight: '400', // Oi only has one weight
//   display: 'swap',
// });

const cherryBombOne = Cherry_Bomb_One({
  subsets: ['latin'],
  weight: '400', // Cherry Bomb One has only 400
  display: 'swap',
});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const cascadiaMono = Geist_Mono({
//   variable: "--font-cascadia-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cherryBombOne.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
